.Dd 29 July 2012
.Dt CHISTKAD 1
.Os
.Sh NAME
.Nm chistkad
.Nd Daemon program used internally by libchistka.
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
This is not the program you are looking for. See chistka(1) and unchistka(1)
instead.
.Pp
This program is used internally by libchistka to perform certain operations
asynchronously and independently of the host program. Do not invoke it
yourself.
